---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age17glck6pghyahjjlq9d5vln7pl3egwlfpz0489m5nr3xf0zg7qdzqux3nlm"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age17glck6pghyahjjlq9d5vln7pl3egwlfpz0489m5nr3xf0zg7qdzqux3nlm"
