apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:1AOdiuGkH8z/eulC8AWP/juRcfiEgM9kS2FRicpUPAMD+b6nBrlnCA==,iv:qekzpju7vdP1glwb3+NbufKTR7Xo+oB9T3TFMIh3VRQ=,tag:aJAAHbSUWuNa03EPy0hi8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17glck6pghyahjjlq9d5vln7pl3egwlfpz0489m5nr3xf0zg7qdzqux3nlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRGcvNmJUTlF0OVpSelRT
            d3RZc29FdUw2Y1lqaTNWcFkwcDVOSlppd2tFCnVQK29hOHU2UG83cXhaTmZwQjJm
            UnhWSWlMYnZTaEFTdVFPTGQwVmF1QjAKLS0tIFZMYUllY1JSUlRuZ3Vpc1pnSG9U
            cEorUy9UV2NON1djUTA2L2tHUnFSSFEKdCmvJdqNdZwhb5oNC0J9V+EH9zx5Ut8k
            rb5YzbTyK4svJef80xGSzLpoM9ptIB1Bs/Ju0b4i5uWpMJYS4TrH1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T09:19:59Z"
    mac: ENC[AES256_GCM,data:C5yXLVzEBLJd/nywww/i/sDsDSWjWiFJthTyCclaq3QjfTCy1ZYTeaqc3byaWk7FsTIfwblbpPsCiunT9nxTBOOde80/Sa9l64P9qs0CEuYmfzkF1gvkD7KOK5wFCwCcYPmx16O2NrtEJEnW1zZY4d6s4xHwMW7aMj0F8+sV3do=,iv:6TYkCIvQoG7KWCGfCYBrxG1SY4QeSQLYpu7bA6yx/kA=,tag:kGHQVewv2+gvAfLQYDGbIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
