apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:JXfT3V8tyrg5XnY0zbBvYWHx1NMKBAjciEFuSUKzurqO2cRxqTAu2YIshP+S9/fp7BaHsm8qhJuXA54lITvP1DDLpOwOTiwsPsPoSbMjXJ3dj+QzMXQqPEiVrtDz3g==,iv:2BEWgi43z49azFjSUSgvfC5Qz9sCliy4DwoxJhG/+QA=,tag:K4yVrZqUgaqSwGrb4PFngg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:mykq93P7nHrb,iv:uYcri1ZrDBJLVVhJsnv3P5FbQ28LW0R40sCkM69wb1g=,tag:5fUtlTt8vxwbjCa+yWqjWQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sVYV3I0jzMmoDQS6SvngdbwKXw==,iv:gSPe17Gk1/mFfuz7VCwa5p7ENmkbntIvmSyitDq5HLQ=,tag:S8mkK5/ByrHmWwF7tv61yw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ziShptZ8atjFyxJiZs6FtPIU2zR+fGBeYTSTa4R7elP8w2sP,iv:K23xXyvQVFkuTU7Dxk+tD8UEvIYo6PlaYU3h6Qp3gtU=,tag:KjKR69FdY23miaYfwojQ5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17glck6pghyahjjlq9d5vln7pl3egwlfpz0489m5nr3xf0zg7qdzqux3nlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMENLSmVWTDhCQXVJWkNQ
            eEUreXR1TFpWK3VFKzZDMjR5OHlOYmh2WkRFCktlY0NtT1RpQm5zWWE0RHpiMzc3
            WVRJc0lVRU41RC9NQUZIeUdzWWdlSjgKLS0tIGdaMC85V2QwZk9DcUxsczdBK0Fo
            SDlBMmtWRm9pNkdNZUdPam9saWsybzQKZJjdw+/ax5lI+2p/tcd9WP+42CLOqP+9
            G3DA2MUtdP71MKNvQwgcUO3yuOAMcR7q3/8zMunBQHULRVjVsIr2IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T13:07:43Z"
    mac: ENC[AES256_GCM,data:nZGV4MVXphMYfEnxgx7GWt+V3e+0vqGXgrK6GtAK2DW1EcNKnhM6DcgeJ7ZA1y3NHb3OkavzhXCl9X6O0vvB/TKZPCssmEay+be+92D6UR/hxl2Pz8+pMV7hbslZkm9hl8tQCHY8szk9Ll2wgWRHU7c91ktVZjd1yBXJg1fq0PI=,iv:Wdj6nmI81mbLmbwmkZINEL9+eoIcYY3dYGzpaN0epCU=,tag:hOgPl2OC/nV5z/bZ/ZNG8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
