apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Ptsh3pizqcayKE/cG9kuX/HssAWsXk+yJ9o/p/1+fHl0sLaW95aA00lpJQk8Xcb4gb//C88Ay26E4XM3Wl6MvAcKTJZMkyiAxUBk5qFnRhTgG0biClT0bitc0JZcKg==,iv:KvseuijXMMKCAfEZehhqE39ErVHzusrBaFPoPI1eHh0=,tag:8lom5XghfZKJ7t4LQ9tPhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17glck6pghyahjjlq9d5vln7pl3egwlfpz0489m5nr3xf0zg7qdzqux3nlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTG5hajRtaGxMem9xMUpv
            eTRnZ21yVXYwMTdTZ1ByQmwveklwVUZhS1ZNCm9IbzZ5VEtvNFp1VktWcGJMNkQz
            c0MvRzJKaFBBUml3Z1Z4SDBNK1AzWVEKLS0tIEU4R3luSStaOW1LVzEwaTl3Rm9J
            dzZyZVdkTXh2ZTBkM0d1ZGNXNC9neE0KCTAIxnxKm8tex6oqvFKtmik3gSrhYY2P
            aIErqT2iH7trIWjjkgvz4oh0uBhXC3LihJHVow7SKPJGRCtvDXMKzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T12:06:35Z"
    mac: ENC[AES256_GCM,data:OKD9vmES89bi/vTq49tZVe8HyuA/QdenuAvPSu8RLwCcypZ7nImF8ldgcXeyJU8xFdDeKb9udA8twu3XtBB5YdKAndu/0JRhTTUL4mLHgURl7noRbAbsfFDa5OfgwSR7skdxk+BWt7Pm8dDVrfOZdFJKj2p1b0mLKm+lsBXN6GM=,iv:jGtBZlOsABfs1zhx9iim+Lx/nVkAVOUGJdGpujnUVdg=,tag:sJZbYdnTQEIlgAorK+IMJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
