apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:PKHGtHqr2nQEgqCwMPDsbqwBgeELt/ytN/QcxUpuKIg=,iv:pVEmBthIe+FrXJQGrvVJVrZhZkW8E/ckwLR8ol8vSME=,tag:08n/hV2tX7ESun7uJQkGzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17glck6pghyahjjlq9d5vln7pl3egwlfpz0489m5nr3xf0zg7qdzqux3nlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SEwzcEhLM0ZPYkdOR2p3
            M09VSjZ4RElraUMwa05EUy9NWTN6eXd6YnpRCjNNalFHV05sV0xwMmtpNGtTSlI1
            S0xSMEQ4NFRjRXpSUjFWWG41QVc3Y0EKLS0tIEZPbEY5bXZwWWt4SmR3dXRzdkxo
            MExNR3hYR3M2ZlRkVWlqM2twTEhWZlUK9Mu07AmRp+E7q989HKVfZHyq5MOcZoOz
            gcorsC1yyTGAnQYuR0LuaqYzFBD5ySRCbX4obSHKI2i8k61H1RK4hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T09:19:59Z"
    mac: ENC[AES256_GCM,data:P5usCcQTAEtm9iL9dmDxLTrFpS7qc4WSkeo8XYPB5BHpgFbCjR+yY3DrcbrbLcFYPUFZX3fnF6DxxwzE9Goyxd/S1XDsgB3ACwsRUBZejzL7q71qFIuzk/bwn4EBLkIJBIhmtawcflt4LJ6T8ZXkyVueCUpWW3w9yrJa5FF4adA=,iv:urt4fzqQH0waP00EbhR/wl24chqFLoEPwKVMD8e3cfQ=,tag:/xVeeIjritH0eHGlK48aeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
