apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:nGQJ7W3lrvwHGAShXORdar6xBp6F1RdzMu5d1hvGVfQ=,iv:LNQuFQLtQzgMJfEGBl+QGuSiD4TYRKkF38BbdaFvqTw=,tag:ec1Qxr1MgaWqMo58txwtYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17glck6pghyahjjlq9d5vln7pl3egwlfpz0489m5nr3xf0zg7qdzqux3nlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL0l3TmhMVkN4aEpENDJu
            c2V6emF5ZXFkVlFRYyswOVR0bGRmbVNDS25vCjhxSlJJa0MzK21WME9yOFd4dW9G
            dDNSN21EVkdYTGhPMWNqL25YWFBLMEUKLS0tIGJRRzdGYTVaU2xXSjYzMEJOeUFK
            dnpxZTlrZ1F3SThrcHU0dW5UY09GdzQKtvhdziIXOUepJThBSywQ+mcZwDW+YLvn
            Qkoh34zhibvsqZbMJvdqihf6hVLpA3ZOWw9UY27RJqg2hSmvR4ISfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T11:12:49Z"
    mac: ENC[AES256_GCM,data:mbdsvqgZMclCGmiH+agUNAsjA6YlX/4HEz2S1VviBPSMbrgYLub/QwHTsV0uNj7qN6zKL/+edJxmunlXLtsqVMBruldWCgWMrLTE504GRvhiBqfLAMzknGGY+D34HXcGrD4UcZtqmVrdNv84s7HPMRK+p15tbiY8QJTXVll+4/8=,iv:6AJMhCNsrLtjwkqOy3pRQFJWufLMX0RUxApjUBKBlnY=,tag:Lx2pm0MYyNvCSfKeVdJGkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
