apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Pwu4w3nPk0j/e6oZ9cNeL+cjrIDWg7TeC4vNGydOyMBt8Ye4PDxNkQ==,iv:rw74D8kwbEnS81WfaFp7TnG19gu2pogAxwxkaCcvE4w=,tag:8GhEENjPADD/+5ZsFXIDgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17glck6pghyahjjlq9d5vln7pl3egwlfpz0489m5nr3xf0zg7qdzqux3nlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxM1ptUlp4V25HYkxXdEFS
            VVFLRjlOVnFHcWgzeVA0azNMYWRzUnRZKzBJCkJqdEhvSnBlNnVVbzhqRGtrNThV
            bS9aYS91T0JBTXI1dU5Rc0cxL2JkVEUKLS0tIHYrUEtKNytTSzlhYmdnNEt4Y0wz
            WnM2UDMvUWN2RTc1cWZiNHorRkNvUjAKtkxfHZQkKUDm5KcSYJflzR9opkrrsvhh
            Q3tE3P3tpJm6PxBp66WmCc6wQthSwjqiI30dD1v/LlWl06X9LH04Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T04:11:25Z"
    mac: ENC[AES256_GCM,data:i9Hn8++lCoxtNWd2pAFj+e5hVRR8SW40TzJWfVB2kbdoYfGlborEzjARbM53IReek1vAnSXGhHLBwUSb18qblpvsyrdPupEHcDqGhlD0STblZYygZZ3APXou5nWx2tEoDUvLd/MMDmPdIMs6KvgQm5hESqcjULe7Ae99CIGMSws=,iv:7CrVNaZYKDTpFt/trMe7BkO2uwnXo4h9r/2/MTaG2dg=,tag:Je9iwoVnxN7VUOT9wJ6Y8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
