apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:yWWJ+4kMt7fk2KA6mBHpyOs8avf6kYrOi8XsufzPW2q6m3J8ZHuLZA==,iv:W/PxG8G95UTqvg1Duy2m6P+tATQXfVvZisxDa3/hm+A=,tag:9zMVX1/oP+V5hw6XcCLhuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17glck6pghyahjjlq9d5vln7pl3egwlfpz0489m5nr3xf0zg7qdzqux3nlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SEhWYXBaZmFpLzZ0UEhD
            bVI3UXhSa2RtT1VTckpSQWZMZlc2OHdZb3cwCmNmRHVxRWRkeXFheW9EVXJzRVdx
            UHZyczA2cHZEbXB5eDAzSHpiRXg1QkkKLS0tIFhYa1FHWFk4M1pTUjAzaHcwMUFo
            SXp2OVdjRHJ0cXB0SnpVQ3FQQ2YrU2cKCPBVYo8+LFnftE2culjZN4mygambfDw1
            FGYGNYVCRkegdQXhkdnz0Kr7y1bBdNM4UTn3Bwdx8eESGciGwny1wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-11T03:48:05Z"
    mac: ENC[AES256_GCM,data:pMT5UWjYQIQTp/k+V+Rs9U03ULEkj4XgzYUnK1JqDzEXbOvxdEhzgeNufi8NxUxzVjnnKaPcFRdVBwvccarAdGCiJU9wkTLluIUHi8aM7Xg/efMnrgU25/8cDIEnOy83SlD2lviCNAAq3cs1uNixjmJeVJt76HYQ16qYvFjtI9I=,iv:x+9UDhJnH0M44KOObYyDOe2JoAxp/jYDMR+YgOCGSHE=,tag:PtJ1Q30/QjzA7U8kNULeOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
