apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:2phHqOo1dWVawkZ2z108yF/YBnvf50bOy314tYAXBr1d9p+i/nZG+A==,iv:+nD2fbVas/ft3d5JgR1PRFla0rrC0PZ5Yl/3/P3YeV0=,tag:dDwk0MS3nxYmPzd85VHl+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17glck6pghyahjjlq9d5vln7pl3egwlfpz0489m5nr3xf0zg7qdzqux3nlm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVGxvTTV5eWpmZzJEcnJN
            ekhoOXFxOWRGQWJlMEYvcDdUZ1BHZTl3ZkRjCk9oRGhpODNWQjJvYzZweFdMd0VO
            eVNaaFU4OXJTSTRRZFY3UlU0ZGRrdVkKLS0tIFY2VmR2QmFTblp4MjBTNko5Z0dx
            TG51dGQ4bmNLUUVURTRSV214dkhPNFUKSSBuev09efNeowO6EJjyEUGJjLBjw9W6
            TekpAB6bwxrMEIYmt2vynbHObDQUmPY4BuTUHKezqKM4Qdo9JgmuZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T13:07:43Z"
    mac: ENC[AES256_GCM,data:7crVKSvcegKmftPqABpTOfatVSrhBJwwLKEZPcQy3lCTOcqlUufOr8uKq2vQIHjszfbzqNaO7TENiz+eRSB6L5nEkyC3tLHrS7H1s4scrhThO7Vsm/xIuqLJtXvnkSTjVMUt/Lpx2ZX/+SZjbvVVyU67wjy554iRuiJRw8eUJos=,iv:dhBZvjadBpV2U7Sd8HqJAiYt4Pmkb8wLP2BLmHF7bKU=,tag:m7XVYY/Ui0pJ/83AxpvybA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
